import type { CheckpointQuestion } from './types'

function item(
  id: string,
  level: number,
  conceptId: string,
  kind: CheckpointQuestion['kind'],
  prompt: string,
  choices: string[],
  correctIndex: number,
  explanation: string,
): CheckpointQuestion {
  return { id, level, conceptId, kind, prompt, choices, correctIndex, explanation }
}

export const CHECKPOINT_POOL: CheckpointQuestion[] = [
  item('l1a', 1, 'choices-cost', 'scenario', 'You can take a $60 evening shift or help a friend move for free. You like the friend and you need the $60. The opportunity cost of helping them move is:', ['The $60 shift you turn down', 'Zero, because friendship is not money', 'The friend’s truck', 'Your whole monthly rent'], 0, 'The next best option you give up is the paid shift.'),
  item('l1b', 1, 'choices-cost', 'decision', 'Groceries you planned are $40. A game you did not plan is also $40. You can afford only one. The stronger sort is:', ['Groceries are the need in this pair; the game is a want you can delay', 'The game is a need because you will be bored', 'Both are needs if you want them', 'Price decides need versus want'], 0, 'Wanting something does not make it a need. The food was already in the plan.'),
  item('l1c', 1, 'goals-plan', 'decision', '“Save more” becomes a usable goal when you add:', ['An amount and a time, such as $200 in eight weeks', 'A slogan on the phone wallpaper', 'A higher credit limit', 'A new subscription to track moods'], 0, 'A goal you can fund names the dollars and the date.'),
  item('l1d', 1, 'goals-plan', 'calc', 'You want $240 in 8 weeks. An even weekly slice is:', ['$30', '$240', '$8', '$60'], 0, '240 ÷ 8 = 30. That is the transfer to schedule.'),
  item('l1e', 1, 'money-behavior', 'scenario', 'A banner says the sale ends tonight. You did not plan the purchase. Present bias is:', ['The pull to grab the deal now and ignore next week’s bills', 'A law that sales must end at midnight', 'The same thing as a low APR', 'Proof the item is a need'], 0, 'The timer makes now feel bigger than the bill that arrives later.'),
  item('l1f', 1, 'money-behavior', 'scenario', 'Your pay rises $40 a week and restaurants quietly rise $40 too. That pattern is:', ['Lifestyle creep', 'Compound growth', 'A grace period', 'Diversification'], 0, 'The raise never reaches a goal because spending rose with it.'),

  item('l2a', 2, 'human-capital', 'compare', 'A $150 course lets you pick up shifts that pay $25 more a week. Ignoring other costs, the course fee is covered in about:', ['6 weeks of the extra pay', 'One day, because learning is priceless', '150 weeks', 'It can never pay off'], 0, '150 ÷ 25 = 6. The comparison is extra pay versus the cost.'),
  item('l2b', 2, 'get-hired', 'decision', 'An interviewer asks for a time you solved a problem. The stronger answer includes:', ['What happened, what you did, and the result', '“I am a people person” and nothing else', 'Your favorite movie', 'A promise that you will never disagree'], 0, 'A specific example is evidence they can believe.'),
  item('l2c', 2, 'pay-forms', 'calc', 'You earn $16 an hour for 30 hours and time-and-a-half for 2 more hours. Gross pay is:', ['$528', '$512', '$480', '$32'], 0, '30×16 = 480. Overtime is 1.5×16×2 = 48. Total 528.'),
  item('l2d', 2, 'pay-forms', 'compare', 'Which pay can change every week even if you work the same hours?', ['Tips or commission', 'A fixed salary with no overtime', 'A gift from a relative', 'A rent payment'], 0, 'Tips and commission follow customers and sales, not just the clock.'),
  item('l2e', 2, 'paycheck-story', 'interpret', 'A stub shows gross $400, withholding $72, net $328. The amount that can land in checking is:', ['$328', '$400', '$72', '$472'], 0, 'Net is what remains after the deduction. Gross is before it.'),
  item('l2f', 2, 'tax-papers', 'scenario', 'A weekend gig sends a 1099 and withheld nothing. A careful move is:', ['Set money aside for the tax you may owe at filing', 'Ignore it because only W-2 jobs are taxed', 'Ask the gig app to call it a gift', 'Spend the whole deposit because filing is optional'], 0, 'No withholding means the yearly tax was not prepaid.'),
  item('l2g', 2, 'benefits', 'compare', 'Two jobs pay the same hourly rate. One includes a health plan you would otherwise buy. The fuller comparison uses:', ['Pay plus the dollar value of the plan', 'Only the hourly rate', 'Only the office snacks', 'Which logo you like'], 0, 'Benefits are part of compensation.'),
  item('l2h', 2, 'tax-papers', 'compare', 'Your next $100 of pay is taxed at 12%, but tax for the whole year is about 8% of income. Those two numbers are:', ['The marginal rate, then the effective rate', 'Both the sales tax', 'The deductible, then the premium', 'APY and a dividend'], 0, 'Marginal is the rate on the next dollar. Effective is the share of all income that went to tax.'),

  item('l3a', 3, 'checking-life', 'decision', 'Payroll says they will only pay by direct deposit. You need:', ['An account that can receive the deposit', 'A stock certificate', 'A paper IOU', 'A credit card with no checking'], 0, 'Direct deposit needs a deposit account. Checking is the everyday one.'),
  item('l3b', 3, 'move-money', 'scenario', 'You wrote a check and the balance has not dropped yet. You should:', ['Leave that amount unspent until it clears', 'Spend it again because it is still there', 'Call it profit', 'Tear up your own record of the check'], 0, 'An uncleared check is already promised.'),
  item('l3c', 3, 'fees-safety', 'scenario', 'Balance $8, ride $14. Letting the bank cover it may:', ['Trigger an overdraft fee on top of the ride', 'Increase your APY', 'Be required by deposit insurance', 'Erase the ride from your history'], 0, 'Overdraft coverage is a fee, not a gift.'),
  item('l3d', 3, 'fees-safety', 'interpret', 'FDIC or NCUA insurance mainly protects you if:', ['The bank or credit union fails', 'You overspend on purpose', 'A store raises prices', 'You forget a password and never report it'], 0, 'Deposit insurance is about the institution failing, not about your spending choices.'),
  item('l3e', 3, 'savings-growth', 'compare', '4% APY on savings and 4% APR on a loan are:', ['Opposite directions: one pays you, one charges you', 'The same product', 'Both illegal', 'Both types of sales tax'], 0, 'APY describes earnings with compounding. APR describes a borrowing price.'),
  item('l3f', 3, 'savings-growth', 'calc', 'You move $25 from checking to savings each week for 10 weeks. Savings rises by:', ['$250, before interest', '$25', '$10', '$2.50'], 0, '25 × 10 = 250. Interest would be extra, not a substitute for the transfers.'),

  item('l4a', 4, 'cashflow-budget', 'interpret', 'Rent is the same each month. Groceries change. Rent is best labeled:', ['Fixed and recurring', 'A one-time discretionary splurge', 'A dividend', 'An asset'], 0, 'It is agreed and it comes back. Groceries are the variable line.'),
  item('l4b', 4, 'cashflow-budget', 'calc', 'Net pay this month is $1,200. Rent and transit are $800. Everything else must fit in:', ['$400', '$2,000', '$800', '$1,200'], 0, '1,200 − 800 = 400 left for food, phone, and wants.'),
  item('l4c', 4, 'buffers', 'decision', 'Insurance you know is due in four months should be:', ['Filled a little each payday in a sinking fund', 'Put on a card the week it is due', 'Ignored until the letter arrives', 'Paid from a payday loan by default'], 0, 'A named future bill is what a sinking fund is for.'),
  item('l4d', 4, 'prices-move', 'scenario', 'Savings earn 1% and prices rise about 3%. Buying power of those savings:', ['Tends to fall', 'Must rise because of the interest', 'Is set by your credit score', 'Cannot change'], 0, 'If prices outrun interest, the same dollars buy less.'),
  item('l4e', 4, 'how-you-pay', 'calc', 'Rice is $2 for 1 lb or $5 for 3 lb. The cheaper pound is:', ['The 3 lb bag, about $1.67 a pound', 'The $2 bag, because 2 is smaller than 5', 'They are equal', 'Whichever has a brighter sign'], 0, '5 ÷ 3 is about 1.67, which beats $2.'),
  item('l4f', 4, 'shop-smart', 'scenario', 'A $1 trial renews at $96 a year unless you cancel. Before you start, you:', ['Find how to cancel and set a reminder', 'Assume trials never bill anyone', 'Treat it as a scholarship', 'Share your banking password with the ad'], 0, 'The contract is the renewal, not the word trial.'),
  item('l4g', 4, 'dont-get-played', 'scenario', 'A text uses your bank’s name and asks you to tap a link and enter a one-time code. You:', ['Open the bank your usual way and ignore the link', 'Reply with the code so they can “fix” it', 'Buy gift cards because the text sounds scared', 'Post the code for friends to check'], 0, 'You go to the institution. You do not hand a code to a surprise text.'),
  item('l4h', 4, 'dont-get-played', 'decision', 'Someone opened a card in your name. After you tell the card company, a strong next step is:', ['A credit freeze so new lenders cannot easily open more accounts', 'Post your Social Security number so friends can watch it', 'Ignore reports for a year', 'Buy a gift card for the “agent” who texted you'], 0, 'A freeze blocks new credit pulls. It is different from locking one card you already have.'),

  item('l5a', 5, 'card-anatomy', 'interpret', 'You pay the full statement balance by the due date and the card has a grace period. Ordinary new purchases usually:', ['Avoid interest', 'Always accrue interest from the swipe', 'Become grants', 'Lower your APY'], 0, 'The grace period is the point of paying the statement in full.'),
  item('l5b', 5, 'use-credit', 'calc', 'Limit $1,000 and balance $250. Utilization is:', ['25%', '75%', '4%', '250%'], 0, '250 ÷ 1,000 = 0.25.'),
  item('l5c', 5, 'use-credit', 'scenario', 'Paying only the minimum mostly:', ['Covers interest and a little principal, so the balance lingers', 'Erases the balance every month', 'Raises your savings APY', 'Is required to keep deposit insurance'], 0, 'Minimums are built to last. Extra principal is what shrinks the loan.'),
  item('l5d', 5, 'reputation', 'decision', 'A debt you do not recognize shows on a report. You:', ['Dispute it with the bureau and the company that reported it', 'Ignore reports because they are fiction', 'Apply for three new cards the same day to hide it', 'Pay a stranger who texted an offer to “delete” it'], 0, 'Errors can be disputed. Random texts that promise deletion are another scam.'),
  item('l5e', 5, 'loan-math', 'calc', 'Loan A is $150 a month for 24 months. Loan B is $90 a month for 60 months. Total paid is:', ['A $3,600 and B $5,400, so A costs less overall', 'B costs less because 90 is smaller than 150', 'They cost the same', 'Impossible to know without a logo'], 0, '150×24 = 3,600. 90×60 = 5,400. The smaller month is the larger total.'),
  item('l5f', 5, 'use-credit', 'compare', 'A secured card is different from a typical unsecured card because:', ['You put down a deposit that backs the limit', 'It cannot affect a report', 'The deposit is a scholarship', 'It has no due date'], 0, 'The deposit is collateral while you build history.'),

  item('l6a', 6, 'car-life', 'calc', 'Payment $200, insurance $120, fuel and upkeep about $90. Monthly ownership cost to plan for is about:', ['$410', '$200', '$90', '$120'], 0, 'Add the piles. The lender is only one of them.'),
  item('l6b', 6, 'car-life', 'interpret', 'Depreciation means:', ['The car is worth less as time and miles pass', 'The loan APR fell', 'Insurance became optional', 'Fuel is free after year two'], 0, 'Resale value dropping is a cost even in a quiet month.'),
  item('l6c', 6, 'cover-the-car', 'scenario', 'You cause damage and the other repair is above your liability limit. You should expect:', ['The policy to pay up to the limit and you to face what remains', 'Every dollar to vanish because you had any insurance', 'The other driver to owe you', 'Deposit insurance to pay the crash'], 0, 'A limit is a cap. FDIC does not cover crashes.'),
  item('l6d', 6, 'debt-path', 'compare', 'Two debts: 22% APR and 8% APR. Extra money shrinks interest fastest on:', ['The 22% debt', 'The 8% debt', 'Whichever has the prettier app', 'Neither, extra payments are not allowed'], 0, 'The higher rate is the expensive one to leave sitting.'),
  item('l6e', 6, 'debt-path', 'scenario', '$200 until Friday, repay $250. That offer is:', ['A very expensive short loan', 'A typical checking fee', 'A grant', 'A retirement match'], 0, 'Fifty dollars for a few days is a huge price.'),
  item('l6f', 6, 'debt-path', 'decision', 'Bankruptcy is best described as:', ['A last legal resort with long credit consequences', 'A coupon for more shopping', 'Required before you can open savings', 'The same thing as a grace period'], 0, 'It is a legal process, not a spending strategy.'),
  item('l6g', 6, 'debt-path', 'scenario', 'A friend asks you to cosign a loan and a store offers a $300 speaker as rent-to-own for $40 a week for a year. The careful read is:', ['You may owe the friend’s loan, and the speaker can cost far more than $300', 'Cosigning is only a character reference', 'Rent-to-own is always cheaper than buying', 'Neither choice can affect your credit'], 0, 'A cosigner is a backup borrower. Weekly rent-to-own payments can dwarf the cash price.'),

  item('l7a', 7, 'first-lease', 'calc', 'First month rent $850 and deposit $850, plus a $50 application fee. Move-in cash is about:', ['$1,750', '$850', '$50', '$900'], 0, '850 + 850 + 50. The deposit does not replace rent.'),
  item('l7b', 7, 'first-lease', 'decision', 'Two roommates share a $90 power bill. A sturdy split is:', ['A written share and a date the money is due', 'Whoever remembers pays, forever', 'Put it on one person’s card and never talk again', 'Skip power so the lease is cheaper'], 0, 'Shared bills need a record or they become a fight.'),
  item('l7c', 7, 'renter-risk', 'scenario', 'A pipe soaks your laptop. The landlord’s building policy typically:', ['Does not replace your laptop', 'Buys you a new computer automatically', 'Pays your groceries', 'Is the same as health insurance'], 0, 'The building policy covers the building. Your things need your policy.'),
  item('l7d', 7, 'risk-tools', 'interpret', 'Premium, deductible, and limit mean:', ['What you pay to keep coverage, what you pay first on a claim, and the cap', 'Three names for the same fee', 'Taxes on a paycheck', 'Parts of a stock dividend'], 0, 'Those three words are the core of almost every policy.'),
  item('l7e', 7, 'risk-tools', 'compare', 'Disability insurance is mainly for:', ['Replacing income if you cannot work', 'Fixing a dented bumper', 'Covering a landlord’s roof', 'Raising a credit score overnight'], 0, 'Health insurance pays medical bills. Disability pays you when work stops.'),
  item('l7f', 7, 'risk-tools', 'calc', 'A covered loss is $2,500. The deductible is $500 and the limit is far higher. You pay:', ['$500 and the policy can pay $2,000', 'Nothing', '$2,500', 'Only the premium that month'], 0, 'You cover the deductible. The insurer handles the rest inside the limit.'),

  item('l8a', 8, 'training-cost', 'calc', 'A program costs $9,000. A grant covers $2,000 and a scholarship covers $1,000. You borrow the rest. Principal borrowed is:', ['$6,000', '$9,000', '$3,000', '$12,000'], 0, '9,000 − 3,000 of aid you do not repay = 6,000 borrowed. Interest is extra.'),
  item('l8b', 8, 'training-cost', 'compare', 'A scholarship differs from a student loan because:', ['You do not repay the scholarship if you keep its rules', 'A scholarship always has a higher APR', 'Loans never need to be repaid', 'They are the same form'], 0, 'Grants and scholarships reduce the bill. Loans become debt.'),
  item('l8c', 8, 'which-path', 'calc', 'Training means missing a $280 net weekly check for 8 weeks and paying $400 in fees. Cash given up is about:', ['$2,640', '$400', '$280', '$8'], 0, '8 × 280 = 2,240, plus 400.'),
  item('l8d', 8, 'which-path', 'decision', 'A credential is worth weighing when:', ['It changes the jobs or pay you can actually get', 'It looks impressive and nothing else', 'It is the most expensive option', 'A stranger in a comment said so'], 0, 'The labor market has to care, or the paper is a souvenir.'),
  item('l8e', 8, 'human-capital', 'scenario', 'You can keep a steady hourly job or pause for training you cannot cash-flow. A complete comparison includes:', ['Tuition, lost pay, and the realistic job after', 'Only the campus photos', 'Only this week’s mood', 'The highest tuition, because price equals quality'], 0, 'Both paths need numbers, including the paychecks you will not receive.'),
  item('l8f', 8, 'pay-forms', 'interpret', 'A salaried offer does not state hours. You should still ask:', ['What a normal week looks like, because salary does not cap effort by itself', 'Nothing, salary means you leave at noon', 'Only the brand of laptop', 'Whether salary is the same as tips'], 0, 'Salary is a set amount. The hours can still run long.'),
  item('l8g', 8, 'training-cost', 'compare', 'A program’s sticker price is $20,000. Gift aid is $8,000. The net price before loans is:', ['$12,000', '$20,000', '$8,000', '$28,000'], 0, 'Net price subtracts gift aid. A loan does not reduce the price; it delays it.'),

  item('l9a', 9, 'why-invest', 'decision', 'Money you may need for rent in three months belongs in:', ['Savings you will not have to sell in a downturn', 'One speculative coin', 'The riskiest stock you can find', 'A friend\'s cash app with no record'], 0, 'Near-term money stays out of volatile markets.'),
  item('l9b', 9, 'why-invest', 'interpret', 'Compound growth means:', ['Returns can themselves earn returns over time', 'Prices never fall', 'A guaranteed doubling every year', 'The same thing as sales tax'], 0, 'Growth on top of growth needs time. It is not a promise about next month.'),
  item('l9c', 9, 'markets', 'compare', 'A bond is closest to:', ['A loan you make to a government or company', 'Ownership of every company in the country', 'A debit card', 'An insurance deductible'], 0, 'Bonds are debt. Stocks are ownership.'),
  item('l9d', 9, 'markets', 'interpret', 'A dividend is:', ['A share of profits a company may pay owners', 'A fee you owe the fund every day', 'The deductible on a claim', 'Withholding on a W-4'], 0, 'Dividends are not guaranteed. A capital gain is separate: selling for more than you paid.'),
  item('l9e', 9, 'build-portfolio', 'compare', 'Diversification helps because:', ['One failure is less likely to sink the whole pile', 'It removes all risk', 'It raises every APY to the same number', 'It replaces an emergency fund'], 0, 'Spreading risk is not the same as deleting risk.'),
  item('l9f', 9, 'build-portfolio', 'scenario', 'A yearly fund fee of 1% versus 0.05% on a similar holding matters because:', ['The higher fee repeats and compounds against you', 'Fees under 1% are always zero', 'The expensive fund is safer by law', 'Fees are refunded by deposit insurance'], 0, 'A small percent, every year, is a large long-run slice.'),

  item('l10a', 10, 'balance-sheet', 'calc', 'Savings $3,000, investments $1,000, loan $2,500. Net worth is:', ['$1,500', '$6,500', '$2,500', '$3,000'], 0, 'Assets 4,000 − liability 2,500 = 1,500.'),
  item('l10b', 10, 'balance-sheet', 'scenario', 'Someone earns a lot and also borrows for every upgrade. They can have:', ['High income and low or negative net worth', 'No liabilities by definition', 'Automatic financial independence', 'A higher FDIC limit because of the income'], 0, 'Income is a flow. Net worth is what remains after debts.'),
  item('l10c', 10, 'retire', 'scenario', 'A job matches your retirement contribution up to 3% of pay. If you contribute nothing:', ['You miss the match', 'The employer still deposits the match', 'Social Security doubles', 'Your student loans are forgiven'], 0, 'The match is pay that depends on your contribution.'),
  item('l10d', 10, 'retire', 'compare', 'A Roth-style account differs from a traditional-style account mainly in:', ['When the tax is paid, if you follow the rules', 'Roth accounts cannot hold funds', 'Traditional accounts are gift cards', 'Only one of them is legal'], 0, 'The concept is the timing of tax, not a brand.'),
  item('l10e', 10, 'retire', 'interpret', 'Social Security is best treated as:', ['One layer of retirement income funded by payroll taxes, not the whole plan', 'A replacement for all saving', 'A type of payday loan', 'Deposit insurance'], 0, 'It is a base for many people. It is not a complete strategy.'),
  item('l10f', 10, 'why-invest', 'decision', 'Before raising risky investing, a sturdy order is:', ['Keep a cash buffer, then invest money you can leave alone', 'Empty savings into one stock', 'Borrow to invest so the timeline is shorter', 'Skip the buffer because markets only rise'], 0, 'The emergency fund and the long-term pile have different jobs.'),
  item('l10g', 10, 'retire', 'decision', 'Naming a beneficiary on a retirement account means:', ['You say who receives it if you die', 'You raise this year’s match', 'You skip Social Security tax', 'The account becomes a checking account'], 0, 'The beneficiary is the instruction. It is not a contribution.'),

  item('l11a', 11, 'buy-home', 'calc', 'Home price $200,000. You put 10% down. The loan principal starts near:', ['$180,000', '$20,000', '$200,000', '$10,000'], 0, '10% of 200,000 is 20,000 down. The loan is the rest, before fees.'),
  item('l11b', 11, 'buy-home', 'interpret', 'PMI on a small down payment is:', ['A lender-required cost because they take more risk', 'The same bill as property tax', 'A type of stock dividend', 'Optional candy at closing'], 0, 'PMI protects the lender. You pay the premium.'),
  item('l11c', 11, 'buy-home', 'calc', 'The home could sell for $210,000 and you still owe $160,000. Equity is about:', ['$50,000', '$210,000', '$370,000', '$160,000'], 0, 'Value minus loan. Equity is the part you own.'),
  item('l11d', 11, 'buy-home', 'decision', 'Closing costs are:', ['Fees due to finish the purchase, separate from the down payment', 'The same thing as the first grocery run', 'Refunded by FDIC', 'Only paid if you rent'], 0, 'Budget them beside the down payment or the purchase stalls.'),
  item('l11e', 11, 'first-lease', 'compare', 'Renting versus buying in a given year should compare:', ['All monthly housing costs, flexibility, and how long you will stay', 'Only the mortgage sticker against rent', 'Only the paint colors', 'Which option has a pool in the ad'], 0, 'Taxes, insurance, maintenance, and the chance you move all belong in the sheet.'),
  item('l11f', 11, 'buy-home', 'scenario', 'A mortgage payment of $1,100 does not include tax and insurance of $300. Housing cash needed is about:', ['$1,400 plus upkeep', '$1,100', '$300', '$800'], 0, 'The lender’s line is not the whole house.'),
  item('l11g', 11, 'buy-home', 'compare', 'An adjustable-rate mortgage that starts cheaper than a fixed rate is risky because:', ['The rate and payment can rise later', 'The down payment is refunded', 'PMI becomes a stock dividend', 'Escrow deletes property tax'], 0, 'A teaser payment is not the payment you may owe after the adjustment.'),

  item('l12a', 12, 'venture', 'calc', 'Drinks sold for $500. Supplies and the booth cost $320. Profit before valuing your time is:', ['$180', '$500', '$320', '$820'], 0, 'Revenue minus costs. Your unpaid hours are still a real tradeoff.'),
  item('l12b', 12, 'venture', 'scenario', 'Customers owe you $300 and you already paid for supplies. Profit might look fine while:', ['Cash in the account is still tight', 'Taxes disappear', 'Revenue becomes a grant', 'The booth fee is optional'], 0, 'Profit and cash are not the same day.'),
  item('l12c', 12, 'venture', 'decision', 'Pricing a product only to match a competitor, while ignoring your costs, risks:', ['Selling a lot and still losing money', 'Automatic profit', 'FDIC coverage of the loss', 'A lower self-employment tax by magic'], 0, 'Price has to clear costs and still pay you.'),
  item('l12d', 12, 'venture', 'interpret', 'Self-employment tax matters because:', ['No employer is sending payroll tax in for you', 'Business income is never taxed', 'It replaces sales tax at the register', 'It is a kind of PMI'], 0, 'Gig and business income can owe both income tax and self-employment tax.'),
  item('l12e', 12, 'give-and-enough', 'decision', 'Financial independence means:', ['Must-pay costs can be covered without a paycheck, usually from savings and investments', 'Never working again starting tomorrow, no matter the math', 'A credit limit high enough to retire', 'Owning a logo'], 0, 'It is a numbers target for your life, not a mood.'),
  item('l12f', 12, 'give-and-enough', 'decision', 'A giving plan that survives is:', ['A budgeted amount that does not steal the rent', 'Whatever is left after impulse buys, if anything', 'A new loan each holiday', 'Skipping insurance so you can donate the premium once'], 0, 'Giving is a value with a line. It is not funded by breaking the rest of the plan.'),
  item('l12g', 12, 'venture', 'calc', 'Costs are $200. You sell each item for $10. Break-even, before paying yourself, is:', ['20 items', '10 items', '200 items', '2 items'], 0, '200 ÷ 10 = 20. Fewer sales and you are still in the hole.'),
]

export function questionsForLevel(level: number): CheckpointQuestion[] {
  return CHECKPOINT_POOL.filter((q) => q.level === level)
}
