import type { EduConcept, LessonChoiceContent, SourceRef } from './types'

const refs = (ka: string, ng: string, js: string, tx: string): SourceRef[] => [
  { framework: 'khan-academy-tx-pfl', ref: ka },
  { framework: 'ngpf-semester', ref: ng },
  { framework: 'jumpstart-cee-2021', ref: js },
  { framework: 'texas-pfl-teks', ref: tx },
]

function choice(prompt: string, strong: LessonChoiceContent, weak: LessonChoiceContent): EduConcept['lesson']['choice'] {
  return { prompt, options: [strong, weak] }
}

function concept(row: EduConcept): EduConcept {
  return row
}

/** Original concept catalog. Sources name the idea that informed the objective, not copied lessons. */
export const CONCEPTS: EduConcept[] = [
  concept({
    id: 'choices-cost',
    title: 'Every choice spends something',
    category: 'decisions',
    level: 1,
    prerequisites: [],
    objectives: [
      'Name the opportunity cost of a real choice between time and money',
      'Sort a purchase into need or want and say what you give up',
    ],
    covers: ['financial-decision-making', 'needs-wants', 'scarcity', 'opportunity-cost', 'tradeoffs'],
    sources: refs(
      'Earning and spending: scarcity and choice',
      'Behavioral economics: opportunity cost',
      'Spending 12 — people choose among alternatives',
      'PFL: scarcity, choice, and opportunity cost',
    ),
    lesson: {
      why: 'You cannot keep the afternoon and the paycheck from the same hour.',
      points: [
        'Scarcity means something runs out: money, time, or energy.',
        'Opportunity cost is the next best thing you did not pick.',
        'A need keeps you safe and able to work. A want is everything else, and wants still matter — they just should not eat the rent.',
      ],
      deep: 'Economists call the forgone option the opportunity cost even when no cash changes hands. A free concert still costs the shift you skipped.',
      choice: choice(
        'Saturday can be a $70 shift or a free day in the park you have wanted all month. The opportunity cost of the shift is:',
        { id: 'park', label: 'The park day you skip', reaction: 'Yes. The cost of the shift is the next best use of that time.', strong: true },
        { id: 'zero', label: 'Nothing, because the park is free', reaction: 'Free of charge is not free of tradeoffs. You still spend the day.' },
      ),
    },
    introduce: ['explore-home', 'scenario:demo-opportunity-cost'],
    practice: ['leave-home', 'shop', 'scenario:demo-opportunity-cost'],
    reinforce: ['shop'],
    systems: ['time', 'guide', 'grocery'],
    missions: ['first-day'],
    legacyTopicIds: ['unit-01-t1'],
    experience: 'The first day at home forces a look around, then a choice to leave. Later, grocery runs and the opportunity-cost scenario replay the same tradeoff with prices attached.',
  }),
  concept({
    id: 'goals-plan',
    title: 'A goal with a date',
    category: 'decisions',
    level: 1,
    prerequisites: ['choices-cost'],
    objectives: [
      'Turn a wish into an amount and a rough date',
      'Say which goal gets the next dollar and why',
    ],
    covers: ['goals', 'financial-planning'],
    sources: refs(
      'Saving: goals',
      'Budgeting: goal setting',
      'Saving 12 — saving for a goal',
      'PFL: planning and goals',
    ),
    lesson: {
      why: '“Be rich” does not tell you what to do on payday.',
      points: [
        'A usable goal names the amount, the date, and why it matters.',
        'Short goals (this month’s groceries) and long goals (a move-out fund) can both be true. The plan says which one the next deposit feeds.',
      ],
      choice: choice(
        'You want $300 for a move-out cushion in about 10 weeks. The most useful next step is:',
        { id: 'slice', label: 'Set aside about $30 each week and track it', reaction: 'A date and a slice you can actually move is a plan.', strong: true },
        { id: 'hope', label: 'Wait until a big windfall shows up', reaction: 'Hope is not a date. A small repeating transfer is.' },
      ),
    },
    introduce: ['goal-set'],
    practice: ['transfer-savings', 'goal-set'],
    reinforce: ['payday'],
    systems: ['goals', 'phone'],
    missions: ['first-day'],
    legacyTopicIds: ['unit-01-t1'],
    experience: 'Character creation already asks for life goals. Saving and payday later show whether those goals get a real transfer.',
  }),
  concept({
    id: 'money-behavior',
    title: 'Your brain spends first',
    category: 'decisions',
    level: 1,
    prerequisites: ['choices-cost'],
    objectives: [
      'Spot present bias in a “buy it now” moment',
      'Notice lifestyle creep when income rises and spending rises with it',
    ],
    covers: ['behavioral-economics', 'present-bias', 'lifestyle-creep'],
    sources: refs(
      'Behavioral economics in personal finance',
      'Behavioral economics unit: present bias',
      'Spending 12 — influences on spending decisions',
      'PFL: decision making and spending influences',
    ),
    lesson: {
      why: 'The checkout line is designed to feel urgent.',
      points: [
        'Present bias means the treat today feels larger than the bill next week.',
        'A pause — a list, a night, a walk outside the store — is a tool, not a punishment.',
        'Lifestyle creep is when a raise disappears into nicer defaults before you notice.',
      ],
      choice: choice(
        'A notification says the shoes are 20% off for two hours. You did not plan on shoes. A strong move is:',
        { id: 'pause', label: 'Leave the page and check the plan tonight', reaction: 'A timer is a sales tool. The plan can still say yes tomorrow.', strong: true },
        { id: 'now', label: 'Buy now so the discount is not “wasted”', reaction: 'A discount on something you were not going to buy is not savings.' },
      ),
    },
    introduce: ['shop'],
    practice: ['shop', 'scenario:demo-opportunity-cost'],
    reinforce: ['payday'],
    systems: ['grocery', 'phone'],
    missions: [],
    legacyTopicIds: ['unit-13-t1'],
    experience: 'FreshMart and pop-up spending scenarios are the practice. The lesson names the bias after the player has felt the pull.',
  }),
  concept({
    id: 'human-capital',
    title: 'Skills are an asset',
    category: 'earning',
    level: 2,
    prerequisites: ['goals-plan'],
    objectives: [
      'Explain human capital as skills that raise what you can earn',
      'Compare a short training cost with a change in pay',
    ],
    covers: ['human-capital', 'careers'],
    sources: refs(
      'Careers and human capital',
      'Career: education and earnings',
      'Earning Income 12.2–12.4 — education, training, credentials',
      'PFL: education, skills, and earning',
    ),
    lesson: {
      why: 'The job offer is not magic. It is paying for what you can already do.',
      points: [
        'Human capital is the mix of skills, credentials, and reputation you can take to the next job.',
        'Training has a cost now (time, tuition, lost shifts) and a possible pay difference later. Compare those, do not collect diplomas as trophies.',
      ],
      choice: choice(
        'A weekend certificate costs $200 and is required for a role that pays about $40 more a week. A reasonable read is:',
        { id: 'payback', label: 'It can pay for itself in a few weeks if you actually get the hours', reaction: 'Cost versus the extra pay is the comparison that matters.', strong: true },
        { id: 'always', label: 'Any certificate is worth it, price ignored', reaction: 'A credential only helps if someone pays more for it or it unlocks work you want.' },
      ),
    },
    introduce: ['goal-set'],
    practice: ['get-hired', 'interview'],
    reinforce: ['payday'],
    systems: ['jobs', 'office', 'college'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'Summit hiring and Merridian College are the two doors: earn now with the skills you have, or spend time building new ones.',
  }),
  concept({
    id: 'get-hired',
    title: 'From application to offer',
    category: 'earning',
    level: 2,
    prerequisites: ['human-capital'],
    objectives: [
      'List the steps from looking to offer: search, apply, interview, decide',
      'Answer an interview question with a specific example',
    ],
    covers: ['job-search', 'applications', 'interviews'],
    sources: refs(
      'Careers: getting hired',
      'Career: job search and interviews',
      'Earning Income 12.1 — job choices and expected pay',
      'PFL: employment and earning income',
    ),
    lesson: {
      why: 'Diane does not hire a resume she never sees.',
      points: [
        'Search where the work actually is, apply with the facts they asked for, then interview with a real example — not “I am a hard worker.”',
        'An offer is still a decision. Pay, hours, and how you get home all count.',
      ],
      choice: choice(
        'The interviewer says, “Tell me about a time you handled a mistake.” A stronger answer:',
        { id: 'story', label: 'Name the mistake, what you did next, and what changed', reaction: 'A specific story is evidence. A slogan is not.', strong: true },
        { id: 'slogan', label: 'Say you never make mistakes', reaction: 'Nobody believes that, and it hides how you fix things.' },
      ),
    },
    introduce: ['interview'],
    practice: ['get-hired', 'interview'],
    reinforce: ['payday'],
    systems: ['office', 'dialogue'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'The Summit interview is the classroom: you cannot get the job without checking and without answering Diane.',
  }),
  concept({
    id: 'pay-forms',
    title: 'How pay is calculated',
    category: 'earning',
    level: 2,
    prerequisites: ['get-hired'],
    objectives: [
      'Compute straight hourly pay and a simple overtime hour',
      'Tell salary, tips, commission, and gig income apart',
    ],
    covers: ['hourly-pay', 'salary', 'overtime', 'tips', 'commissions', 'gig-income'],
    sources: refs(
      'Earning: wages, salary, and other pay',
      'Career / taxes: forms of income',
      'Earning Income 12.5 — wages and the labor market',
      'PFL: sources of income',
    ),
    lesson: {
      why: '“Twenty an hour” is not the same promise as “twenty thousand a year” or “20% of sales.”',
      points: [
        'Hourly pay is rate times hours. Overtime is often a higher rate after a weekly threshold — check the offer, do not assume.',
        'Salary is a set amount per period, not a promise about how many hours the work takes.',
        'Tips and commission move with customers and sales. Gig pay often arrives without an employer withholding taxes for you.',
      ],
      deep: 'A $20 hourly job at 18.5 hours is about $370 gross this week. A salary that sounds larger can still pay less per hour if the week runs long.',
      choice: choice(
        'You work 2 extra hours past a 40-hour week and the offer says overtime is 1.5× a $16 rate. Those two hours gross:',
        { id: 'ot', label: '$48', reaction: '1.5 × 16 × 2 = 48. The base hours are a separate line.', strong: true },
        { id: 'base', label: '$32', reaction: 'That is straight time. Overtime in this offer is time-and-a-half.' },
      ),
    },
    introduce: ['get-hired'],
    practice: ['payday', 'get-hired'],
    reinforce: ['payday'],
    systems: ['jobs', 'paystubs'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'Summit pay is hourly. The stub and the offer are where the player sees rate × hours before tax.',
  }),
  concept({
    id: 'paycheck-story',
    title: 'What actually hits the account',
    category: 'earning',
    level: 2,
    prerequisites: ['pay-forms'],
    objectives: [
      'Read gross, deductions, and net on a pay stub',
      'Explain why the deposit is smaller than hours × rate',
    ],
    covers: ['paychecks', 'paystubs', 'gross-net', 'deductions', 'withholding', 'payroll-tax', 'income-tax'],
    sources: refs(
      'Taxes and paychecks: reading a stub',
      'Taxes: withholding and net pay',
      'Earning Income 12.6 — taxes fund public services',
      'PFL: taxes, withholding, and net income',
    ),
    lesson: {
      why: 'The deposit is the number that can pay rent. The gross number is the number before the government and benefits take their lines.',
      points: [
        'Gross is pay before deductions. Net is what remains.',
        'Withholding is an estimate of income and payroll taxes taken out during the year, not a surprise tip to your boss.',
        'This city’s early job uses a simple withholding rate so you can see the gap. Real stubs add Social Security, Medicare, and sometimes benefits.',
      ],
      choice: choice(
        'Gross is $370 and withholding is 18%. The direct deposit is about:',
        { id: 'net', label: '$303', reaction: '370 − about 67 = 303. That is the spendable line.', strong: true },
        { id: 'gross', label: '$370', reaction: 'That is before withholding. The account will not show the gross.' },
      ),
    },
    introduce: ['payday'],
    practice: ['payday'],
    reinforce: ['payday'],
    systems: ['paystubs', 'bank', 'phone'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-16-t1'],
    experience: 'The first direct deposit opens a short explanation that uses the player’s own gross, tax, and net. The stub stays on the phone.',
  }),
  concept({
    id: 'tax-papers',
    title: 'Tax papers and the yearly true-up',
    category: 'earning',
    level: 2,
    prerequisites: ['paycheck-story'],
    objectives: [
      'Say what a W-4, W-2, and 1099 are for',
      'Explain that withholding is an estimate and filing compares it with the year’s tax',
      'Tell a marginal rate from an effective rate, and a deduction from a credit',
    ],
    covers: ['brackets', 'filing', 'tax-documents', 'self-employment-tax'],
    sources: refs(
      'Filing and tax documents',
      'Taxes: W-2, W-4, 1099, brackets',
      'Earning Income 12.6–12.7 — taxes and payroll programs',
      'PFL: filing and payroll documents',
    ),
    lesson: {
      why: 'The stub is the weekly estimate. Filing is the yearly correction.',
      points: [
        'A W-4 tells an employer how much to withhold. A W-2 reports wages and withholding after the year. A 1099 often shows gig or contract income with little or no withholding.',
        'Brackets tax slices of income at different rates. The rate on the next dollar is the marginal rate. The share of all income that actually went to tax is the effective rate. You do not lose the whole check to the top bracket.',
        'A deduction lowers the income that gets taxed. A credit lowers the tax bill itself.',
        'Gig income can owe both income tax and self-employment tax because no employer sent payroll tax in for you.',
      ],
      deep: 'If too much was withheld, the filing often comes back as a refund. That refund was your money all year — not a bonus from the government.',
      choice: choice(
        'A summer gig pays you with no taxes taken out and sends a 1099. You should expect:',
        { id: 'owe', label: 'To set money aside because filing may show tax due', reaction: 'No withholding means the yearly bill was not prepaid.', strong: true },
        { id: 'free', label: 'No tax, because it was not a “real job”', reaction: 'The work still counts as income. The form is the clue.' },
      ),
    },
    introduce: ['payday'],
    practice: ['lesson:unit-16-l1', 'quiz:unit-16-t1'],
    reinforce: ['payday'],
    systems: ['paystubs', 'college', 'office'],
    missions: [],
    legacyTopicIds: ['unit-16-t1'],
    experience: 'The live sim withholds a single rate. The lesson and checkpoint carry W-2, W-4, 1099, and brackets so the simple stub does not become the whole tax story.',
  }),
  concept({
    id: 'benefits',
    title: 'Pay is more than the deposit',
    category: 'earning',
    level: 2,
    prerequisites: ['paycheck-story'],
    objectives: [
      'Name a benefit that has dollar value besides wages',
      'Describe unemployment insurance as temporary income after a job loss, not a paycheck bonus',
    ],
    covers: ['employee-benefits', 'unemployment-insurance'],
    sources: refs(
      'Benefits and insurance through work',
      'Career: benefits and total compensation',
      'Earning Income 12.7–12.9 — benefits and public insurance',
      'PFL: compensation beyond wages',
    ),
    lesson: {
      why: 'Two offers with the same hourly rate can be worth different amounts.',
      points: [
        'Health coverage, retirement match, and paid sick time are part of pay even when they are not on the net line.',
        'Unemployment insurance is a limited benefit if you lose a job and meet the rules. It is not a reason to skip work, and it does not replace a full check.',
      ],
      choice: choice(
        'Offer A pays $1 less an hour but includes a health plan you would otherwise buy yourself for $200 a month. A fair comparison:',
        { id: 'total', label: 'Put a monthly dollar value on the plan, then compare', reaction: 'Benefits are pay. Price them.', strong: true },
        { id: 'rate', label: 'Take the higher hourly rate automatically', reaction: 'The rate is only one line of the offer.' },
      ),
    },
    introduce: ['get-hired'],
    practice: ['get-hired', 'lesson:unit-11-l1'],
    reinforce: ['payday'],
    systems: ['jobs', 'office'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'Summit is a simple hourly job. The offer conversation and the career lesson are where benefits get priced before a later job menu exists.',
  }),
  concept({
    id: 'checking-life',
    title: 'A checking account that receives pay',
    category: 'banking',
    level: 3,
    prerequisites: ['paycheck-story'],
    objectives: [
      'Open and use a checking account for deposits and spending',
      'Explain direct deposit and why an employer asks for it',
    ],
    covers: ['checking', 'banks', 'credit-unions', 'deposits', 'atms', 'debit-cards', 'direct-deposit'],
    sources: refs(
      'Checking accounts and payments',
      'Checking unit',
      'Saving 12 — financial institutions',
      'PFL: accounts at banks and credit unions',
    ),
    lesson: {
      why: 'Cash in a pocket cannot take a direct deposit.',
      points: [
        'Checking is the account day-to-day money moves through: pay in, bills and card purchases out.',
        'Banks and credit unions both offer accounts. A credit union is member-owned; compare fees and access, not the logo.',
        'Direct deposit sends net pay in without a paper check. An ATM or debit card spends from that balance — the receipt is not extra money.',
      ],
      choice: choice(
        'You are hired, but payroll will not pay you in cash. You need:',
        { id: 'checking', label: 'An account that can receive a direct deposit', reaction: 'That is the checking account’s job in this city.', strong: true },
        { id: 'invest', label: 'A stock account first', reaction: 'Investing comes after a place for pay to land and a buffer to fall back on.' },
      ),
    },
    introduce: ['open-checking'],
    practice: ['deposit', 'payday', 'open-checking'],
    reinforce: ['payday'],
    systems: ['bank', 'paystubs'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-07-t1', 'unit-06-t1'],
    experience: 'FirstCity Bank is required before Summit will hire you, because pay is a direct deposit. That sequence is the lesson.',
  }),
  concept({
    id: 'move-money',
    title: 'Moving and watching money',
    category: 'banking',
    level: 3,
    prerequisites: ['checking-life'],
    objectives: [
      'Match a debit purchase or transfer to the account it left',
      'Describe a check as a written instruction, not cash until it clears',
    ],
    covers: ['transfers', 'checks', 'transaction-monitoring'],
    sources: refs(
      'Payments, checks, and monitoring',
      'Checking: reconciling transactions',
      'Spending 12 — payment methods',
      'PFL: payment methods and account records',
    ),
    lesson: {
      why: 'The balance on Monday is a story. The transactions are the sentences.',
      points: [
        'A transfer moves money between your accounts. A debit purchase moves it to a store. A check tells the bank to pay someone when they deposit it — the money can leave later than the moment you hand the paper over.',
        'Monitoring means reading the list and catching what you do not recognize.',
      ],
      choice: choice(
        'You wrote a $40 check and your balance did not drop yet. A careful read is:',
        { id: 'clear', label: 'It may still clear. Do not spend that $40 again.', reaction: 'Uncleared checks are spoken-for money.', strong: true },
        { id: 'free', label: 'The money is still yours to spend', reaction: 'That double-spend is how accounts go negative.' },
      ),
    },
    introduce: ['open-checking'],
    practice: ['deposit', 'withdraw', 'shop'],
    reinforce: ['shop'],
    systems: ['bank', 'ledger', 'phone'],
    missions: [],
    legacyTopicIds: ['unit-07-t1'],
    experience: 'Deposits, withdrawals, and the phone ledger are the practice. Checks are taught here because the live city pays electronically.',
  }),
  concept({
    id: 'fees-safety',
    title: 'Fees, overdrafts, and who insures deposits',
    category: 'banking',
    level: 3,
    prerequisites: ['checking-life'],
    objectives: [
      'Give an example of an overdraft and a way to avoid it',
      'Explain deposit insurance as protection if the institution fails, not if you overspend',
    ],
    covers: ['fees', 'overdrafts', 'fdic-ncua', 'account-security'],
    sources: refs(
      'Account fees and deposit insurance',
      'Checking: overdrafts and fees',
      'Saving 12 — institutions and safety of deposits',
      'PFL: account costs and financial institutions',
    ),
    lesson: {
      why: 'A $4 coffee can become a $38 story if the account cannot cover it.',
      points: [
        'An overdraft is spending more than the available balance. Some banks pay it and charge a fee; some decline the card. Opt in only if you understand the fee.',
        'FDIC (banks) and NCUA (credit unions) insurance protects deposits up to the stated limit if the institution fails. It does not refund fees or fraud you ignored.',
        'Security is a locked phone, a real login, and a habit of reading alerts.',
      ],
      choice: choice(
        'Your balance is $6 and lunch is $9. The safer card behavior is:',
        { id: 'stop', label: 'Do not force the purchase through', reaction: 'Declining a swipe is cheaper than an overdraft fee.', strong: true },
        { id: 'over', label: 'Let it overdraft so you can eat out', reaction: 'The fee can cost more than the meal.' },
      ),
    },
    introduce: ['open-checking'],
    practice: ['surprise-expense', 'shop'],
    reinforce: ['bill-due'],
    systems: ['bank', 'ledger'],
    missions: [],
    legacyTopicIds: ['unit-07-t1'],
    experience: 'Low balances after bills and surprise expenses are when overdraft risk shows up. The bank lesson names the fee before it becomes a habit.',
  }),
  concept({
    id: 'savings-growth',
    title: 'Savings, interest, and APY',
    category: 'banking',
    level: 3,
    prerequisites: ['checking-life'],
    objectives: [
      'Move money into savings on purpose',
      'Explain APY as the yearly rate including compounding, and how it differs from a loan APR',
    ],
    covers: ['savings-accounts', 'interest', 'apy', 'apr-vs-apy', 'saving-strategies'],
    sources: refs(
      'Saving and compound interest',
      'Saving: APY and accounts',
      'Saving 12 — interest and compound growth',
      'PFL: saving and interest',
    ),
    lesson: {
      why: 'Checking is a hallway. Savings is a room you do not walk through every hour.',
      points: [
        'Interest is what the institution pays you for keeping deposits. APY shows the year with compounding included, so you can compare accounts.',
        'APR on a loan is the yearly borrowing price. APY on savings is what you earn. Same percent sign, opposite direction.',
        'A strategy is a repeating transfer, not a mood.',
      ],
      choice: choice(
        'Account A advertises 4% APR on a loan. Account B advertises 4% APY on savings. They are:',
        { id: 'diff', label: 'Not the same kind of rate', reaction: 'One is the cost of borrowing. The other is what deposits earn.', strong: true },
        { id: 'same', label: 'Identical, so either is “good”', reaction: 'The letters tell you who pays whom.' },
      ),
    },
    introduce: ['open-savings', 'transfer-savings'],
    practice: ['transfer-savings', 'deposit'],
    reinforce: ['payday'],
    systems: ['bank', 'savings'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-08-t1'],
    experience: 'Opening savings and transferring from checking is the live action. The APY lesson sits on that transfer, not in a vacuum.',
  }),
  concept({
    id: 'cashflow-budget',
    title: 'Money in, money out',
    category: 'managing',
    level: 4,
    prerequisites: ['checking-life', 'paycheck-story'],
    objectives: [
      'Build a simple cash-flow picture: income minus bills and spending',
      'Label an expense as fixed, variable, discretionary, or recurring',
    ],
    covers: ['budgeting', 'cash-flow', 'fixed-expenses', 'variable-expenses', 'discretionary', 'recurring-expenses'],
    sources: refs(
      'Budgeting and cash flow',
      'Budgeting unit',
      'Spending 12 — budgeting',
      'PFL: budgeting income and expenses',
    ),
    lesson: {
      why: 'A budget is a plan for the cash you actually receive, not a punishment list.',
      points: [
        'Cash flow is money in minus money out over a period. If it stays negative, savings shrink or debt grows.',
        'Fixed costs stay put (rent). Variable costs move (groceries, power). Discretionary costs are the wants. Recurring means they come back — subscriptions included.',
      ],
      choice: choice(
        'Rent is $700 every month and groceries were $80, then $140. Rent is:',
        { id: 'fixed', label: 'Fixed and recurring', reaction: 'The amount is agreed and it returns on a schedule.', strong: true },
        { id: 'disc', label: 'Discretionary, because you chose the apartment once', reaction: 'Choosing it once does not make this month’s rent optional.' },
      ),
    },
    introduce: ['bill-due'],
    practice: ['shop', 'bill-due', 'payday'],
    reinforce: ['shop'],
    systems: ['bills', 'ledger', 'grocery', 'phone'],
    missions: [],
    legacyTopicIds: ['unit-12-t1'],
    experience: 'Rent and other bills hit the calendar. Groceries hit the cart. The phone ledger is the budget you already lived.',
  }),
  concept({
    id: 'buffers',
    title: 'Emergency funds and sinking funds',
    category: 'managing',
    level: 4,
    prerequisites: ['savings-growth', 'cashflow-budget'],
    objectives: [
      'Explain why an emergency fund is separate from spending money',
      'Start a sinking fund for a bill you can see coming',
    ],
    covers: ['emergency-fund', 'sinking-funds'],
    sources: refs(
      'Emergency savings',
      'Saving: emergency and sinking funds',
      'Saving 12 — saving for emergencies',
      'PFL: saving for unexpected events',
    ),
    lesson: {
      why: 'The surprise repair is not a surprise if you own anything that can break.',
      points: [
        'An emergency fund covers a job gap or a real shock. A common target is a few months of must-pay bills, built slowly.',
        'A sinking fund is for a cost you can name in advance: insurance due twice a year, a trip, a deposit. You fill it on purpose so the month it is due does not wreck the budget.',
      ],
      choice: choice(
        'You know car insurance will be due in four months. The fitting tool is:',
        { id: 'sink', label: 'A sinking fund you add to each payday', reaction: 'Named, dated, and filled early.', strong: true },
        { id: 'card', label: 'A credit card when the bill arrives', reaction: 'That turns a planned cost into interest.' },
      ),
    },
    introduce: ['transfer-savings'],
    practice: ['transfer-savings', 'surprise-expense'],
    reinforce: ['payday'],
    systems: ['savings', 'random-expenses', 'bills'],
    missions: [],
    legacyTopicIds: ['unit-08-t1', 'unit-12-t1'],
    experience: 'Random expenses already fire in the sim. Savings transfers are how the player builds the buffer those events test.',
  }),
  concept({
    id: 'prices-move',
    title: 'Inflation and the price on the shelf',
    category: 'managing',
    level: 4,
    prerequisites: ['cashflow-budget'],
    objectives: [
      'Explain inflation as prices rising so a dollar buys less',
      'Separate sales tax on a purchase from income tax on pay',
    ],
    covers: ['inflation', 'purchasing-power', 'sales-vs-income-tax'],
    sources: refs(
      'Inflation and purchasing power',
      'Budgeting / investing: inflation',
      'Spending 12 and Saving 12 — inflation',
      'PFL: inflation and taxes on purchases versus income',
    ),
    lesson: {
      why: 'The same grocery list can cost more in the fall than it did in September.',
      points: [
        'Inflation means the general level of prices rises. Purchasing power is how much stuff a dollar still buys.',
        'Sales tax is added at the register. Income tax is tied to what you earn. They are different bills with different forms.',
      ],
      choice: choice(
        'Your savings earn 1% APY and prices rise about 3% this year. The purchasing power of that savings pile:',
        { id: 'down', label: 'Likely falls', reaction: 'If prices outrun the interest, the same dollars buy less.', strong: true },
        { id: 'up', label: 'Rises, because you earned interest', reaction: 'Interest helps, but it has to beat inflation to gain buying power.' },
      ),
    },
    introduce: ['scenario:demo-price-spike'],
    practice: ['shop', 'scenario:demo-price-spike'],
    reinforce: ['shop'],
    systems: ['grocery', 'scenarios'],
    missions: [],
    legacyTopicIds: ['unit-03-t1', 'unit-05-t1'],
    experience: 'The price-spike scenario and the grocery cart are the lived version. Macro lessons at the college go deeper if the player wants the big picture.',
  }),
  concept({
    id: 'how-you-pay',
    title: 'Which way you pay',
    category: 'managing',
    level: 4,
    prerequisites: ['checking-life', 'money-behavior'],
    objectives: [
      'Choose cash, debit, or credit for a purchase and name the risk',
      'Spot a hidden fee or a “discount” that is not one',
    ],
    covers: ['payment-choice', 'comparison-shopping', 'hidden-fees', 'total-cost', 'advertising'],
    sources: refs(
      'Payment methods and consumer choices',
      'Budgeting and consumer skills: payment choices',
      'Spending 12 — payment methods and advertising',
      'PFL: consumer decisions and payment methods',
    ),
    lesson: {
      why: 'The sticker is not always the amount that leaves your life.',
      points: [
        'Cash and debit spend money you have. Credit spends money you promise to repay.',
        'Compare unit prices and the total after fees, delivery, and tax. Advertising is paid to move you, not to tutor you.',
      ],
      choice: choice(
        'Two stores sell the same rice. One is $2 for 1 lb. The other is $5 for 3 lb. The better unit price is:',
        { id: 'bulk', label: 'About $1.67 a pound at the second store', reaction: '5 ÷ 3 is the comparison, not the bigger sticker.', strong: true },
        { id: 'small', label: 'The $2 bag, because the number is smaller', reaction: 'A smaller sticker can still be the expensive pound.' },
      ),
    },
    introduce: ['shop'],
    practice: ['shop'],
    reinforce: ['shop'],
    systems: ['grocery', 'ledger'],
    missions: [],
    legacyTopicIds: ['unit-13-t1'],
    experience: 'Every FreshMart checkout is practice. The cart total is the total cost, not the sale banner.',
  }),
  concept({
    id: 'shop-smart',
    title: 'Contracts, warranties, and subscriptions',
    category: 'managing',
    level: 4,
    prerequisites: ['how-you-pay'],
    objectives: [
      'Find the cancellation and renewal terms before starting a subscription',
      'Decide whether a warranty is worth more than the risk you can cover yourself',
    ],
    covers: ['contracts', 'warranties', 'subscriptions'],
    sources: refs(
      'Consumer protection and contracts',
      'Consumer skills: contracts and warranties',
      'Spending 12 — contracts and consumer protection',
      'PFL: consumer rights and responsibilities',
    ),
    lesson: {
      why: '“Free month” often means “we will bill you on day 31 unless you cancel.”',
      points: [
        'A contract is a promise with consequences. Read price, length, how to cancel, and what happens if you stop paying.',
        'A warranty is insurance-like coverage for a product. It is useful when the repair would hurt and the price is fair. It is optional when you could replace the item from savings.',
        'Subscriptions are recurring on purpose. Put them on the budget the day you start them.',
      ],
      choice: choice(
        'A $9 “trial” renews yearly at $108 unless you cancel in the app. Before you tap start:',
        { id: 'cancel', label: 'Find the cancel path and put a reminder on the calendar', reaction: 'The contract is the renewal, not the trial banner.', strong: true },
        { id: 'later', label: 'Assume you will remember because it is only $9', reaction: 'The $9 is the bait. The $108 is the contract.' },
      ),
    },
    introduce: ['shop'],
    practice: ['shop', 'lesson:unit-20-l1'],
    reinforce: ['bill-due'],
    systems: ['grocery', 'college'],
    missions: [],
    legacyTopicIds: ['unit-13-t1', 'unit-20-t1'],
    experience: 'The grocery and the consumer-protection lesson carry this until a subscriptions shop exists. Bills that recur are the reinforcement.',
  }),
  concept({
    id: 'dont-get-played',
    title: 'Scams, phishing, and identity theft',
    category: 'managing',
    level: 4,
    prerequisites: ['move-money'],
    objectives: [
      'Refuse a request for a code, password, or gift-card payment',
      'List the first moves after a card or identity is misused, including a credit freeze',
    ],
    covers: ['fraud', 'scams', 'phishing', 'identity-theft', 'financial-security'],
    sources: refs(
      'Scams and identity theft',
      'Insurance / consumer: fraud and identity theft',
      'Managing Risk 12 — identity theft and fraud',
      'PFL: protecting against fraud and identity theft',
    ),
    lesson: {
      why: 'Urgency is the scammer’s favorite interest rate.',
      points: [
        'Phishing pretends to be a bank, a boss, or the government to steal a login or a code.',
        'Real institutions do not ask you to buy gift cards or to move money to “keep the account safe.”',
        'If a card is used without you, lock that card, tell the institution, and change the password. If someone is opening accounts in your name, place a credit freeze with the bureaus so new lenders cannot pull the report, then check the reports and file the official identity-theft report.',
      ],
      choice: choice(
        'A text says your bank account is frozen and gives a link to “verify” by typing your password. You:',
        { id: 'app', label: 'Ignore the link and open the bank the way you usually do', reaction: 'You go to them. You do not let them come through a surprise link.', strong: true },
        { id: 'link', label: 'Tap the link quickly so the account is not lost', reaction: 'Speed is the trap. The real app will still be there.' },
      ),
    },
    introduce: ['surprise-expense'],
    practice: ['lesson:unit-21-l1', 'quiz:unit-21-t1'],
    reinforce: ['shop'],
    systems: ['phone', 'bank'],
    missions: [],
    legacyTopicIds: ['unit-21-t1'],
    experience: 'The scam lesson at home is explicit on purpose: you should not have to be robbed to learn the pattern. Surprise bills are a reminder to read who is actually charging you.',
  }),
  concept({
    id: 'card-anatomy',
    title: 'A credit card statement',
    category: 'credit',
    level: 5,
    prerequisites: ['how-you-pay', 'cashflow-budget'],
    objectives: [
      'Find the balance, limit, APR, fees, and due date on a statement',
      'Explain a grace period and when interest starts',
    ],
    covers: ['credit-cards', 'statements', 'credit-limits', 'apr', 'grace-period', 'credit-interest', 'credit-fees'],
    sources: refs(
      'Credit cards and statements',
      'Credit: statements, APR, grace periods',
      'Managing Credit 12 — cost of credit',
      'PFL: credit cards and the cost of borrowing',
    ),
    lesson: {
      why: 'The card is a loan that fits in a pocket.',
      points: [
        'The limit is the maximum the issuer will lend, not a target.',
        'APR is the yearly interest price if you carry a balance. A grace period lets new purchases avoid interest when you pay the statement balance in full by the due date. Cash advances often have no grace period.',
        'Fees — annual, late, foreign — are extra cost on top of interest.',
      ],
      choice: choice(
        'You pay the statement balance in full before the due date. On ordinary new purchases you should expect:',
        { id: 'no-int', label: 'No interest, if the card still offers a grace period', reaction: 'The grace period is the reward for paying the whole statement.', strong: true },
        { id: 'always', label: 'Interest on every purchase no matter what', reaction: 'Interest usually starts when a balance is carried, not when you merely use the card and pay it off.' },
      ),
    },
    introduce: ['credit-card'],
    practice: ['credit-card', 'lesson:unit-09-l1'],
    reinforce: ['shop'],
    systems: ['bank', 'credit'],
    missions: [],
    legacyTopicIds: ['unit-09-t1'],
    experience: 'Applying at the bank creates the card. The statement concepts are taught against that account, and the checkpoint asks the player to read one.',
  }),
  concept({
    id: 'use-credit',
    title: 'Using credit without feeding it',
    category: 'credit',
    level: 5,
    prerequisites: ['card-anatomy'],
    objectives: [
      'Estimate utilization as balance divided by limit',
      'Show why paying only the minimum keeps the balance alive',
    ],
    covers: ['utilization', 'minimum-payments', 'secured-credit', 'unsecured-credit'],
    sources: refs(
      'Using credit and minimum payments',
      'Managing credit: utilization and minimums',
      'Managing Credit 12 — managing credit and debt',
      'PFL: responsible use of credit',
    ),
    lesson: {
      why: 'The minimum payment is designed to be affordable and expensive at the same time.',
      points: [
        'Utilization is how full the card is. High utilization can hurt a score even if you pay on time.',
        'The minimum mostly covers interest and a sliver of principal. The balance can linger for years.',
        'A secured card asks for a deposit that becomes the limit — useful to start a file. An unsecured card does not hold your cash as collateral.',
      ],
      choice: choice(
        'Limit $1,000, statement balance $800. Utilization is about:',
        { id: '80', label: '80%', reaction: '800 / 1000. Lenders notice a card that full.', strong: true },
        { id: '20', label: '20%', reaction: 'That would be $200 of a $1,000 limit.' },
      ),
    },
    introduce: ['credit-card'],
    practice: ['credit-card', 'quiz:unit-09-t1'],
    reinforce: ['shop'],
    systems: ['credit', 'bank'],
    missions: [],
    legacyTopicIds: ['unit-09-t1'],
    experience: 'Once a card exists, spending and the bank screen are the practice. Secured cards are taught for players who cannot qualify yet.',
  }),
  concept({
    id: 'reputation',
    title: 'Reports, scores, and history',
    category: 'credit',
    level: 5,
    prerequisites: ['use-credit'],
    objectives: [
      'Describe what a credit report contains and that you can dispute an error',
      'Name behaviors that move a score: on-time payments, amounts owed, new accounts, history length',
    ],
    covers: ['credit-reports', 'credit-scores', 'credit-history'],
    sources: refs(
      'Credit reports and scores',
      'Credit: reports and scores',
      'Managing Credit 12 — credit reports and scores',
      'PFL: credit reports and scores',
    ),
    lesson: {
      why: 'The score is a rumor with a formula. The report is the story it is based on.',
      points: [
        'A report lists accounts, limits, balances, and whether you paid on time. You can get reports and dispute wrong lines.',
        'Paying on time matters most. Amounts owed, how long you have had credit, new applications, and the mix of accounts also count.',
        'Checking your own report is not the same as a lender pulling it for a new loan.',
      ],
      choice: choice(
        'A bill you do not recognize appears on a report. The useful first move is:',
        { id: 'dispute', label: 'Dispute the error with the bureau and the company', reaction: 'The report should match reality. You are allowed to say it does not.', strong: true },
        { id: 'ignore', label: 'Ignore it because scores are random', reaction: 'Scores follow the report. A wrong debt can follow you into a loan denial.' },
      ),
    },
    introduce: ['open-checking', 'credit-card'],
    practice: ['credit-card', 'quiz:unit-10-t1'],
    reinforce: ['bill-due'],
    systems: ['credit', 'bank', 'bills'],
    missions: [],
    legacyTopicIds: ['unit-10-t1'],
    experience: 'On-time bills and bank activity already move the in-game score. The report lesson explains what that number is pretending to summarize.',
  }),
  concept({
    id: 'loan-math',
    title: 'The full price of a loan',
    category: 'credit',
    level: 5,
    prerequisites: ['card-anatomy'],
    objectives: [
      'Separate principal from the interest you pay to borrow it',
      'Compare two terms by monthly payment and by total paid',
    ],
    covers: ['loans', 'principal', 'loan-terms', 'monthly-payment', 'total-borrowing-cost'],
    sources: refs(
      'Loans, principal, and total cost',
      'Loans: amortization and term',
      'Managing Credit 12 — cost of credit over time',
      'PFL: calculating the cost of borrowing',
    ),
    lesson: {
      why: 'A smaller monthly payment can be the more expensive loan.',
      points: [
        'Principal is the amount you borrowed. Interest is the rent on that money. The term is how long you promise to pay.',
        'Stretching the term lowers the month and raises the total. Always look at both.',
      ],
      deep: 'A $5,000 loan at a high APR for 5 years can cost far more than the same principal for 2 years, even though the longer loan looks “easier” each month.',
      choice: choice(
        'Loan A: $200 a month for 2 years. Loan B: $120 a month for 5 years. Before you pick, you also need:',
        { id: 'total', label: 'The total you will pay on each', reaction: '200×24 and 120×60 are the real price tags.', strong: true },
        { id: 'low', label: 'Only the smaller monthly payment', reaction: 'That is how longer, costlier loans get chosen.' },
      ),
    },
    introduce: ['scenario:car-buy-vs-lease'],
    practice: ['scenario:car-buy-vs-lease', 'car-deal', 'quiz:unit-09-t1'],
    reinforce: ['bill-due'],
    systems: ['scenarios', 'car'],
    missions: [],
    legacyTopicIds: ['unit-09-t1'],
    experience: 'Car and housing deals are where term and total cost become a payment on the calendar. The checkpoint makes the player do the multiplication.',
  }),
  concept({
    id: 'car-life',
    title: 'The cost of getting around',
    category: 'transport',
    level: 6,
    prerequisites: ['loan-math', 'cashflow-budget'],
    objectives: [
      'Add payment, insurance, fuel, and maintenance into a monthly car cost',
      'Explain depreciation as the car being worth less over time',
    ],
    covers: ['car-buying', 'auto-financing', 'depreciation', 'fuel', 'maintenance', 'total-ownership-cost'],
    sources: refs(
      'Transportation and auto loans',
      'Loans / insurance: buying a car',
      'Spending 12 and Managing Credit 12 — large purchases',
      'PFL: transportation decisions',
    ),
    lesson: {
      why: 'The monthly note is the cover of the story. Fuel and tires are the rest of the book.',
      points: [
        'Compare paying cash, financing, leasing, transit, or delaying. Financing means the payment, the APR, and the total.',
        'Depreciation is the drop in what you could sell the car for. It is a cost even in a month with no repair.',
        'A repair fund belongs in the car budget before the car does.',
      ],
      choice: choice(
        'A car payment is $220. Insurance is $130. Fuel and a maintenance average are about $100. The ownership cost to budget is about:',
        { id: 'all', label: '$450', reaction: 'All three piles leave every month, not just the lender’s pile.', strong: true },
        { id: 'pay', label: '$220', reaction: 'That is only the loan. The car still has to be insured and moved.' },
      ),
    },
    introduce: ['car-deal', 'scenario:car-buy-vs-lease'],
    practice: ['car-deal', 'scenario:car-buy-vs-lease'],
    reinforce: ['bill-due', 'surprise-expense'],
    systems: ['car', 'bills', 'scenarios'],
    missions: [],
    legacyTopicIds: ['unit-19-t1'],
    experience: 'AutoMart already compares buy, lease, and walking away, then puts a payment on the calendar. Repairs show up as random expenses.',
  }),
  concept({
    id: 'cover-the-car',
    title: 'Auto insurance as a bill you hope not to use',
    category: 'transport',
    level: 6,
    prerequisites: ['car-life'],
    objectives: [
      'Describe a premium, deductible, and liability limit in a car policy',
      'Connect driving without required coverage to a legal and money risk',
    ],
    covers: ['auto-insurance'],
    sources: refs(
      'Auto insurance',
      'Insurance: auto coverage',
      'Managing Risk 12 — auto insurance',
      'PFL: automobile insurance',
    ),
    lesson: {
      why: 'The car can damage someone else’s life, not just your bumper.',
      points: [
        'The premium is what you pay to keep the policy. The deductible is what you pay first when you file certain claims.',
        'Liability coverage pays others when you are at fault, up to the limit. Collision and comprehensive cover the car itself under the rules of the policy.',
      ],
      choice: choice(
        'You cause a crash and the other driver’s repairs are $8,000. Your liability limit and deductible decide:',
        { id: 'who', label: 'How much the policy pays and what you still owe', reaction: 'Limits cap the insurer. The deductible is your share on covered claims.', strong: true },
        { id: 'zero', label: 'Nothing, because insurance means free repairs', reaction: 'Insurance shifts big risk. It does not erase every dollar.' },
      ),
    },
    introduce: ['car-deal'],
    practice: ['car-deal', 'lesson:unit-17-l1'],
    reinforce: ['bill-due'],
    systems: ['car', 'insurance'],
    missions: [],
    legacyTopicIds: ['unit-17-t1', 'unit-19-t1'],
    experience: 'Buying at AutoMart should pull insurance into the monthly picture. The home insurance lesson reinforces the same premium/deductible language.',
  }),
  concept({
    id: 'debt-path',
    title: 'Getting out, and what not to sign',
    category: 'transport',
    level: 6,
    prerequisites: ['use-credit', 'loan-math'],
    objectives: [
      'Choose a payoff order and say why (highest APR or smallest balance)',
      'Recognize a payday-style loan, rent-to-own, and cosigning as costs you can refuse',
      'Describe bankruptcy as a last legal resort, not a coupon',
    ],
    covers: ['debt-management', 'predatory-lending', 'bankruptcy'],
    sources: refs(
      'Managing debt and costly loans',
      'Managing credit: debt payoff and predatory lending',
      'Managing Credit 12 — managing debt',
      'PFL: debt management and costly credit',
    ),
    lesson: {
      why: 'More borrowing is not a plan for old borrowing.',
      points: [
        'List debts, rates, and minimums. Paying extra on the highest APR shrinks interest fastest. Paying a small balance first can be a motivation tool if you then roll that payment forward.',
        'Payday and title loans often charge a huge cost for a short wait until the next check. Rent-to-own can make a cheap item cost several times its store price. A cheaper path is a payment plan, a credit-union loan, or cutting the expense.',
        'Cosigning means you agree to pay if the other person does not. The debt can land on your report and your budget. Do not sign because someone is in a hurry.',
        'Bankruptcy is a legal process with long consequences for credit and property. It is a last resort when debts cannot be paid, not a strategy to shop more.',
      ],
      choice: choice(
        'A lender offers $200 until Friday and wants $240 back. The careful label is:',
        { id: 'pred', label: 'Very expensive short-term credit', reaction: 'That is a huge cost for a few days. Look for another way.', strong: true },
        { id: 'help', label: 'A normal favor because it is a small amount', reaction: '$40 on $200 for a few days is not a small rate.' },
      ),
    },
    introduce: ['surprise-expense'],
    practice: ['bill-due', 'surprise-expense', 'lesson:unit-09-l1'],
    reinforce: ['payday'],
    systems: ['bills', 'credit', 'random-expenses'],
    missions: [],
    legacyTopicIds: ['unit-09-t1'],
    experience: 'Missed bills and surprise costs are the pressure. The lesson names payday lending before a storefront for it exists.',
  }),
  concept({
    id: 'first-lease',
    title: 'Renting a place',
    category: 'housing',
    level: 7,
    prerequisites: ['cashflow-budget', 'buffers'],
    objectives: [
      'Read a lease for rent, length, deposit, and who pays which utility',
      'Split a shared bill with roommates in a way you can document',
    ],
    covers: ['renting', 'leases', 'deposits-housing', 'utilities', 'roommates'],
    sources: refs(
      'Renting and leases',
      'Budgeting / insurance: renting',
      'Spending 12 — housing decisions',
      'PFL: renting and housing costs',
    ),
    lesson: {
      why: 'The deposit is not rent. You may get it back only if the place is left as agreed.',
      points: [
        'A lease is the contract: monthly rent, how long, late fees, guests, and repairs.',
        'Utilities (power, heat, internet) can rival a chunk of rent. Ask which ones are in the price.',
        'Roommates need a written split. “We’ll figure it out” fails the month someone moves out.',
      ],
      choice: choice(
        'Rent is $900 and you are told the deposit is $900. You should treat the move-in cash need as about:',
        { id: 'both', label: '$1,800 plus any fees and first utilities', reaction: 'Deposit and first rent often leave together.', strong: true },
        { id: 'one', label: '$900, because the deposit replaces rent', reaction: 'The deposit is held, not spent as this month’s rent.' },
      ),
    },
    introduce: ['bill-due'],
    practice: ['bill-due', 'lesson:unit-18-l1'],
    reinforce: ['payday'],
    systems: ['bills', 'home'],
    missions: [],
    legacyTopicIds: ['unit-18-t1'],
    experience: 'Maple rent is already on the calendar. The housing lesson and checkpoint use that bill as the lease in miniature.',
  }),
  concept({
    id: 'renter-risk',
    title: 'Renter’s insurance',
    category: 'housing',
    level: 7,
    prerequisites: ['first-lease'],
    objectives: [
      'Explain that a landlord’s policy does not replace your belongings',
      'Name what a renter’s policy is for',
    ],
    covers: ['renters-insurance'],
    sources: refs(
      'Renters insurance',
      'Insurance: renters policies',
      'Managing Risk 12 — property insurance',
      'PFL: renters insurance',
    ),
    lesson: {
      why: 'If a pipe lets go, the building’s policy cares about the building.',
      points: [
        'Renter’s insurance covers your stuff and often liability if someone is hurt in your place, up to the limits you bought.',
        'The premium is usually small next to replacing a room of belongings. Photograph what you own anyway.',
      ],
      choice: choice(
        'A fire damages your clothes and laptop. The landlord’s policy typically:',
        { id: 'building', label: 'Covers the building, not your laptop', reaction: 'Your things need your policy.', strong: true },
        { id: 'all', label: 'Replaces every tenant’s belongings automatically', reaction: 'That is what people hope. It is not what the landlord bought.' },
      ),
    },
    introduce: ['bill-due'],
    practice: ['lesson:unit-17-l1', 'lesson:unit-18-l1'],
    reinforce: ['surprise-expense'],
    systems: ['home', 'insurance'],
    missions: [],
    legacyTopicIds: ['unit-17-t1', 'unit-18-t1'],
    experience: 'Housing and insurance lessons connect. A future lease flow can require the policy; today the rent bill and the lesson carry it.',
  }),
  concept({
    id: 'risk-tools',
    title: 'Insurance as a tool',
    category: 'housing',
    level: 7,
    prerequisites: ['buffers'],
    objectives: [
      'Define premium, deductible, claim, and coverage limit',
      'Match health, life, and disability coverage to the risk each one is for',
    ],
    covers: ['premiums', 'deductibles', 'claims', 'coverage-limits', 'health-insurance', 'life-disability'],
    sources: refs(
      'Insurance types and policy language',
      'Insurance unit',
      'Managing Risk 12 — insurance decisions',
      'PFL: insurance and risk management',
    ),
    lesson: {
      why: 'You cannot save your way out of every hospital bill, and you should not insure a $30 risk.',
      points: [
        'You pay a premium to transfer a big, rare loss. A deductible is your share before the policy pays. A claim is you asking for that payment. The limit is the maximum.',
        'Health insurance is for medical bills. Disability insurance replaces income if you cannot work. Life insurance pays people who depend on your income if you die. Term coverage is often the simple version of that last one.',
      ],
      choice: choice(
        'A policy has a $1,000 deductible and a $50,000 limit. A covered $4,000 loss usually means:',
        { id: 'share', label: 'You pay $1,000 and the policy can pay the rest, inside the limit', reaction: 'Deductible first, then the insurer, up to the cap.', strong: true },
        { id: 'all', label: 'The insurer pays $4,000 and you pay nothing', reaction: 'The deductible is the part with your name on it.' },
      ),
    },
    introduce: ['surprise-expense'],
    practice: ['lesson:unit-17-l1', 'quiz:unit-17-t1'],
    reinforce: ['car-deal', 'bill-due'],
    systems: ['insurance', 'home', 'random-expenses'],
    missions: [],
    legacyTopicIds: ['unit-17-t1'],
    experience: 'Surprise expenses show uninsured shocks. The insurance lesson is the vocabulary, reused when a car or apartment decision shows up.',
  }),
  concept({
    id: 'training-cost',
    title: 'Paying for more training',
    category: 'education',
    level: 8,
    prerequisites: ['human-capital', 'loan-math'],
    objectives: [
      'Separate scholarships, grants, and work-study pay from loans you must repay',
      'Estimate whether student-loan payments fit the pay the program usually leads to',
      'Use a net price (sticker minus gift aid) and tell a federal student loan from a private one',
    ],
    covers: ['college-costs', 'scholarships', 'grants', 'student-loans'],
    sources: refs(
      'Paying for college and training',
      'Paying for college unit',
      'Earning Income 12.2–12.3 — costs and benefits of education',
      'PFL: financing education',
    ),
    lesson: {
      why: 'A campus tour is not a price.',
      points: [
        'The cost is tuition, fees, housing, food, books, and the wages you do not earn while you study.',
        'Scholarships and grants are gift aid you do not repay if you keep the rules. Work-study is a job. Student loans are debt. Net price is the sticker minus the gift aid, not the number on the brochure.',
        'A federal student loan usually has more flexible repayment than a private loan from a bank. Fill out the federal aid form (FAFSA) before assuming you must borrow privately.',
        'A payment on a large loan can outlive the excitement of the program. Compare it with typical pay in the job you actually want.',
      ],
      choice: choice(
        'A program costs $12,000. You have a $4,000 grant and plan to borrow the rest. You will repay:',
        { id: 'loan', label: 'About $8,000 plus interest, not the grant', reaction: 'The grant reduces what you borrow. Interest applies to the loan.', strong: true },
        { id: 'all', label: 'The full $12,000, because all aid is a loan', reaction: 'Grants are not loans. Read the letter that says which is which.' },
      ),
    },
    introduce: ['lesson:unit-11-l1'],
    practice: ['quiz:unit-11-t1', 'get-hired'],
    reinforce: ['payday'],
    systems: ['college', 'jobs'],
    missions: [],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'Merridian is in the city. Until a financial-aid office exists, the career lesson and checkpoint carry grants versus loans, using the player’s current pay as the comparison.',
  }),
  concept({
    id: 'which-path',
    title: 'Comparing a path',
    category: 'education',
    level: 8,
    prerequisites: ['training-cost', 'pay-forms'],
    objectives: [
      'Compare staying in a job with pausing for training, including lost wages',
      'Name a credential only if it changes the work you can get',
    ],
    covers: ['education-career-compare'],
    sources: refs(
      'Comparing education and career paths',
      'Career: opportunity cost of school',
      'Earning Income 12.3 — comparing education and job options',
      'PFL: career and education decisions',
    ),
    lesson: {
      why: 'School is a purchase made of tuition and of the shifts you do not work.',
      points: [
        'Write both paths for a few years: pay, costs, and the job at the end.',
        'A longer program can be worth it and still be the wrong year to start if you have no buffer.',
      ],
      choice: choice(
        'Training means giving up a $300 weekly net check for 10 weeks, plus $500 in fees. The training’s cash cost includes about:',
        { id: 'both', label: '$3,500', reaction: 'Lost net pay is part of the price: 10 × 300 + 500.', strong: true },
        { id: 'fee', label: '$500', reaction: 'The fee is the visible part. The missing paychecks are the rest.' },
      ),
    },
    introduce: ['get-hired'],
    practice: ['get-hired', 'lesson:unit-11-l1'],
    reinforce: ['payday'],
    systems: ['college', 'jobs', 'office'],
    missions: ['first-opportunity'],
    legacyTopicIds: ['unit-11-t1'],
    experience: 'The player already has a job path at Summit and a college building. The checkpoint uses their own weekly net as the “wages given up” number when it is available.',
  }),
  concept({
    id: 'why-invest',
    title: 'Saving and investing are different jobs',
    category: 'investing',
    level: 9,
    prerequisites: ['buffers', 'prices-move'],
    objectives: [
      'Keep emergency money out of volatile investments',
      'Describe compound growth and a time horizon in plain language',
    ],
    covers: ['saving-vs-investing', 'compound-growth', 'time-horizon', 'risk-return'],
    sources: refs(
      'Saving versus investing',
      'Investing: goals, risk, and compound growth',
      'Investing 12 — risk, return, and long-term goals',
      'PFL: saving and investing',
    ),
    lesson: {
      why: 'The emergency fund is not supposed to be an adventure.',
      points: [
        'Saving is for money you may need soon and cannot watch drop. Investing is for money with years to ride swings in search of higher long-run growth.',
        'Compound growth means returns can earn returns. A longer time horizon gives compounding and recovery more room.',
        'Higher expected return usually comes with a higher chance of a bad year.',
      ],
      choice: choice(
        'You might need $1,000 for a job gap this year. The fitting place for that $1,000 is:',
        { id: 'save', label: 'Savings you can reach without selling in a slump', reaction: 'Near-term money stays boring on purpose.', strong: true },
        { id: 'stock', label: 'A single stock, so it grows faster', reaction: 'It might. It might also be down the week you need rent.' },
      ),
    },
    introduce: ['scenario:investing-intro', 'invest-buy'],
    practice: ['invest-buy', 'transfer-savings'],
    reinforce: ['invest-sell'],
    systems: ['investing', 'bank', 'savings'],
    missions: [],
    legacyTopicIds: ['unit-14-t1'],
    experience: 'The bank invest desk already requires a savings buffer before you buy. That gate is the lesson: safety money first, then risk.',
  }),
  concept({
    id: 'markets',
    title: 'Stocks, bonds, and funds',
    category: 'investing',
    level: 9,
    prerequisites: ['why-invest'],
    objectives: [
      'Contrast a stock, a bond, and a fund',
      'Explain dividends, capital gains, and volatility without treating a good year as a promise',
    ],
    covers: ['stocks', 'bonds', 'mutual-funds', 'index-funds', 'etfs', 'dividends', 'capital-gains', 'volatility'],
    sources: refs(
      'Stocks, bonds, and funds',
      'Investing: asset classes and funds',
      'Investing 12 — stocks, bonds, and funds',
      'PFL: investment types',
    ),
    lesson: {
      why: 'Owning a slice of a company is not the same as lending a city money.',
      points: [
        'A stock is ownership. Its price moves, and some companies pay dividends from profits. A capital gain is profit when you sell for more than you paid; a loss is the opposite.',
        'A bond is a loan to a government or company. You expect interest and the principal back if the borrower pays.',
        'A mutual fund, index fund, or ETF holds many investments. An index fund tracks a list. An ETF often trades through the day like a stock. Volatility is how sharply the price jumps around.',
      ],
      choice: choice(
        'You want one purchase that holds many companies instead of betting on one. The closer match is:',
        { id: 'fund', label: 'A broad fund or ETF', reaction: 'One buy, many holdings. You still can lose money.', strong: true },
        { id: 'one', label: 'The single stock a video said will double', reaction: 'That is a bet on one story, not a basket.' },
      ),
    },
    introduce: ['invest-buy', 'scenario:investing-intro'],
    practice: ['invest-buy', 'invest-sell', 'quiz:unit-15-t1'],
    reinforce: ['invest-buy'],
    systems: ['investing'],
    missions: [],
    legacyTopicIds: ['unit-15-t1'],
    experience: 'The desk sells a growth stock ETF and a bond fund. Buying either is the practice; the price wobble the next day is volatility.',
  }),
  concept({
    id: 'build-portfolio',
    title: 'Spreading risk and watching fees',
    category: 'investing',
    level: 9,
    prerequisites: ['markets'],
    objectives: [
      'Explain diversification as not depending on one company or one idea',
      'Compare a fee that repeats every year with a one-time excitement about a speculative bet',
    ],
    covers: ['diversification', 'investment-fees', 'scheduled-investing', 'speculative-assets'],
    sources: refs(
      'Diversification, fees, and speculative assets',
      'Investing: diversification, fees, and alternatives',
      'Investing 12 — diversification and costs',
      'PFL: managing investment risk and costs',
    ),
    lesson: {
      why: 'A 1% yearly fee sounds tiny until it compounds against you for twenty years.',
      points: [
        'Diversification spreads money so one failure is not the whole future.',
        'Scheduled investing means adding a set amount on a calendar. You buy more shares when prices are low and fewer when they are high, without needing to predict the week.',
        'Speculative assets — including a lot of crypto hype — can go to zero. They are not the emergency fund and they are not a plan by themselves.',
      ],
      choice: choice(
        'Two funds track a similar list. One charges 0.05% a year. The other charges 1% and a flashy app. A cost-aware pick leans:',
        { id: 'low', label: 'Toward the lower yearly fee if the holdings match', reaction: 'Fees are a certain loss. Hype is not a return.', strong: true },
        { id: 'app', label: 'Toward the app, because fees do not matter under 1%', reaction: 'A percent every year is a large slice of long-run growth.' },
      ),
    },
    introduce: ['invest-buy'],
    practice: ['invest-buy', 'invest-sell'],
    reinforce: ['payday'],
    systems: ['investing'],
    missions: [],
    legacyTopicIds: ['unit-14-t1', 'unit-15-t1'],
    experience: 'Owning both the stock ETF and the bond fund is diversification inside the current desk. Fees and speculative warnings live in the lesson and checkpoint until more products exist.',
  }),
  concept({
    id: 'balance-sheet',
    title: 'Net worth is not your paycheck',
    category: 'wealth',
    level: 10,
    prerequisites: ['cashflow-budget', 'loan-math'],
    objectives: [
      'List assets and liabilities and subtract to get net worth',
      'Explain how someone can have a high income and a low or negative net worth',
    ],
    covers: ['assets', 'liabilities', 'net-worth', 'wealth-vs-income'],
    sources: refs(
      'Net worth and wealth',
      'Budgeting / investing: net worth',
      'Saving 12 and Investing 12 — building wealth',
      'PFL: assets, liabilities, and net worth',
    ),
    lesson: {
      why: 'A big week of pay can still leave you poorer if the new debt is bigger.',
      points: [
        'Assets are what you own: cash, balances, investments, a car’s resale value. Liabilities are what you owe.',
        'Net worth is assets minus liabilities. Income is a flow. Wealth is the stock that is left.',
      ],
      choice: choice(
        'You have $2,000 in savings and a $7,000 loan. Ignoring other items, net worth is about:',
        { id: 'neg', label: '−$5,000', reaction: '2,000 − 7,000. Income does not change that subtraction.', strong: true },
        { id: 'pos', label: '$9,000', reaction: 'Adding them pretends the loan is yours to keep.' },
      ),
    },
    introduce: ['payday'],
    practice: ['invest-buy', 'payday', 'credit-card'],
    reinforce: ['bill-due'],
    systems: ['phone', 'bank', 'investing', 'credit'],
    missions: [],
    legacyTopicIds: ['unit-06-t1'],
    experience: 'The phone net-worth snapshot, unlocked with this level, adds up the balances the game already tracks.',
  }),
  concept({
    id: 'retire',
    title: 'Future-you needs a deposit too',
    category: 'wealth',
    level: 10,
    prerequisites: ['why-invest', 'benefits'],
    objectives: [
      'Describe an employer match as extra pay you only get if you contribute',
      'Contrast a workplace plan, a traditional IRA idea, and a Roth idea without picking a product for someone else',
      'Name a beneficiary so an account has instructions if you die',
    ],
    covers: ['retirement', 'employer-match', '401k', 'ira-roth', 'social-security'],
    sources: refs(
      'Retirement accounts and Social Security',
      'Investing: retirement accounts',
      'Investing 12 — retirement saving',
      'PFL: retirement and long-term saving',
    ),
    lesson: {
      why: 'Social Security is a base for many people. It is not a full plan.',
      points: [
        'A 401(k) or similar workplace plan lets you save from pay. A match is the employer adding money when you do — often the best return available, because it is part of pay.',
        'A traditional IRA idea: you may get a tax break now and pay tax when you withdraw in retirement. A Roth idea: you pay tax now and qualified withdrawals later can be tax-free. Rules and income limits are real; the concept is the timing of the tax.',
        'Social Security is funded by payroll taxes and pays a benefit later based on your record. It is one layer, not the whole stack.',
        'A beneficiary is the person who receives an account if you die. Naming one on a workplace plan or IRA is the instruction. A simple will covers the rest of what you own.',
      ],
      choice: choice(
        'Your job matches retirement contributions dollar for dollar up to 3% of pay. Skipping the contribution means:',
        { id: 'leave', label: 'Leaving that match on the table', reaction: 'The match is pay you only receive if you put your share in.', strong: true },
        { id: 'same', label: 'Nothing, because retirement is far away', reaction: 'Far away is why a match has decades to compound.' },
      ),
    },
    introduce: ['payday', 'get-hired'],
    practice: ['invest-buy', 'lesson:unit-14-l1'],
    reinforce: ['payday'],
    systems: ['jobs', 'investing', 'paystubs'],
    missions: [],
    legacyTopicIds: ['unit-14-t1'],
    experience: 'Summit does not yet offer a match. The paycheck and invest desk teach the habit; the checkpoint uses a match example so the idea is ready when a richer job exists.',
  }),
  concept({
    id: 'buy-home',
    title: 'Buying a home is a stack of costs',
    category: 'home',
    level: 11,
    prerequisites: ['first-lease', 'loan-math', 'buffers'],
    objectives: [
      'List down payment, mortgage payment, PMI, tax, insurance, maintenance, and closing costs',
      'Explain equity as the part of the home’s value you actually own',
      'Contrast a fixed rate with an adjustable rate, and name escrow and HOA dues as extra housing bills',
    ],
    covers: [
      'homeownership',
      'mortgages',
      'down-payments',
      'mortgage-interest',
      'pmi',
      'equity',
      'property-taxes',
      'homeowners-insurance',
      'home-maintenance',
      'closing-costs',
    ],
    sources: refs(
      'Home buying and mortgages',
      'Insurance / budgeting: housing and mortgages',
      'Managing Credit 12 and Spending 12 — mortgages and housing',
      'PFL: homeownership costs',
    ),
    lesson: {
      why: 'The mortgage payment is not the cost of the house.',
      points: [
        'A mortgage is a loan secured by the home. The down payment is cash you put in at the start. A smaller down payment can mean PMI, insurance the lender wants because they are more exposed.',
        'Equity is value minus the loan. It grows when you pay principal down or the home’s value rises, and it shrinks if prices fall.',
        'Property tax, homeowners insurance, maintenance, and closing costs (the pile of fees to finish the purchase) belong in the decision, not in a footnote. Escrow is the account that collects tax and insurance with the payment. An HOA due is a neighborhood fee on top of the loan.',
        'A fixed rate keeps the interest rate for the term. An adjustable rate can start lower and then change. The payment you can afford has to survive the higher rate, not just the teaser.',
      ],
      choice: choice(
        'You put 5% down and the lender adds a monthly PMI charge. That charge is:',
        { id: 'ins', label: 'A cost of borrowing with a small down payment', reaction: 'PMI protects the lender. You pay for it.', strong: true },
        { id: 'tax', label: 'The same thing as property tax', reaction: 'Property tax funds local services. PMI is about the loan.' },
      ),
    },
    introduce: ['home-deal', 'scenario:home-rent-vs-buy'],
    practice: ['home-deal', 'scenario:home-rent-vs-buy'],
    reinforce: ['bill-due'],
    systems: ['home', 'scenarios', 'bills'],
    missions: [],
    legacyTopicIds: ['unit-18-t1'],
    experience: 'The home deal already asks the player to compare buying, renting, or waiting, with credit and down-payment gates. The cost sheet unlocked here names every line the payment hides.',
  }),
  concept({
    id: 'venture',
    title: 'A small business is a cash-flow machine',
    category: 'venture',
    level: 12,
    prerequisites: ['cashflow-budget', 'tax-papers', 'loan-math'],
    objectives: [
      'Compute a simple profit as revenue minus costs, and a break-even price',
      'Separate profit on paper from cash in the account',
      'Name a financing and a tax risk of working for yourself, including filing as a sole proprietor',
    ],
    covers: [
      'entrepreneurship',
      'revenue',
      'costs',
      'profit',
      'business-cash-flow',
      'pricing',
      'business-financing',
      'business-taxes',
      'business-risk',
    ],
    sources: refs(
      'Entrepreneurship and self-employment',
      'Career / taxes: self-employment',
      'Earning Income 12.8 — entrepreneurs and business risk',
      'PFL: earning through a business',
    ),
    lesson: {
      why: 'A busy Saturday can still be a losing week.',
      points: [
        'Revenue is what customers pay. Costs are what you spend to serve them. Profit is what remains.',
        'Cash flow can be negative while a sale “counts,” if the customer has not paid or you bought supplies already.',
        'Price has to cover the product, your time, fees, and a margin. Break-even is the sales that exactly cover costs. Financing might be savings, a loan, or a partner — each has a cost.',
        'A sole proprietor is you and the business in one tax life. Profit can owe income tax and self-employment tax even before you pay yourself a “salary.”',
        'Business income is often taxed differently, and you may owe self-employment tax. Risk includes no customers, a broken tool, or a debt the business cannot carry.',
      ],
      choice: choice(
        'You sell $400 of drinks. Cups, ingredients, and the booth fee cost $250. Profit before your own unpaid time is:',
        { id: '150', label: '$150', reaction: '400 − 250. Your hours are still a real cost if you could have worked a shift.', strong: true },
        { id: '400', label: '$400', reaction: 'That is revenue. The booth was not free.' },
      ),
    },
    introduce: [],
    practice: ['lesson:venture', 'quiz:unit-11-t1'],
    reinforce: ['shop', 'payday'],
    systems: ['future-business'],
    missions: [],
    legacyTopicIds: [],
    experience: 'No storefront business exists yet. The checkpoint and venture notes are the practice: price a tiny stand using numbers from the player’s own costs. A later business district can log real revenue against this concept.',
  }),
  concept({
    id: 'give-and-enough',
    title: 'Enough, and giving',
    category: 'venture',
    level: 12,
    prerequisites: ['balance-sheet', 'retire', 'goals-plan'],
    objectives: [
      'Describe financial independence as covering needs from savings and investments, not as a luxury brand',
      'Choose a giving amount that fits the budget instead of the leftover change',
    ],
    covers: ['philanthropy', 'financial-independence'],
    sources: refs(
      'Giving and long-term financial independence',
      'Budgeting: charitable giving and long-term goals',
      'Spending 12 — charitable giving; Investing 12 — long-term goals',
      'PFL: planning, giving, and long-term goals',
    ),
    lesson: {
      why: 'A life plan that never says “enough” will spend every raise.',
      points: [
        'Financial independence means your must-pay life can be covered without a paycheck, usually because savings and investments throw off enough. It is a direction, not a personality.',
        'Giving is a value with a line in the budget. Planned giving beats guilt at the end of the month, and it should not come from the rent.',
      ],
      choice: choice(
        'You want to give $20 a payday to a local food program. The sturdy way is:',
        { id: 'line', label: 'Put $20 in the plan beside the other recurring transfers', reaction: 'Giving becomes a choice you already made, not a scramble.', strong: true },
        { id: 'card', label: 'Put it on a card whenever a post makes you feel guilty', reaction: 'Mood giving is real, and it is how people miss rent.' },
      ),
    },
    introduce: ['goal-set'],
    practice: ['payday', 'transfer-savings'],
    reinforce: ['payday'],
    systems: ['goals', 'phone', 'savings'],
    missions: [],
    legacyTopicIds: [],
    experience: 'Goals chosen at the start can include helping others. Payday and savings transfers are where “enough” and giving either get a number or stay a wish.',
  }),
]

export const CONCEPT_BY_ID: Record<string, EduConcept> = Object.fromEntries(CONCEPTS.map((c) => [c.id, c]))

export function conceptsForLevel(level: number): EduConcept[] {
  return CONCEPTS.filter((c) => c.level === level)
}
